### ISSUE TITLE
Move `.feature` and `.ndjson` files into a root `samples` directory

### ISSUE THREAD

**Issue by mattwynne** [cucumber/compatibility-kit#3]
### 🤔 What's the problem you've observed?

The main `.feature` and `.ndjson` files that are published by the CCK are currently hidden away in the `javascript` folder. We then make a copy of them into the `ruby` folder at build time.

### ✨ Do you have a proposal for making it better?

Move these files into the root of the project. @aurelien-reeves and I have discussed and we think `samples` would be a good name for this directory, since it's not an exhaustive list of Cucumber's features, just a few representative samples taken of the `ndjson` output in different situations.

We'll aim to get a `npm <something>` running in the root that does everything.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by aurelien-reeves** [comment]
https://github.com/cucumber/compatibility-kit/pull/4
