### ISSUE TITLE
move ruby step definitions and code into cucumber-ruby

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/compatibility-kit#44]
### 🤔 What's the problem you've observed?

For Ruby, the step definitions and code to support running the specs sits here, in the CCK repo.

By contrast, for JS and JVM, the step definitions and code lives in the implementation repo, and CCK is just the source of content to feed into that plumbing - features, messages and (illustrative) reference steps.

This presents a few difficulties which we've seen recently:
- When adding a new step or feature in CCK, you can either omit to include the Ruby step definition(s), in which case a `cucumber-ruby` maintainer has to come and add them after the fact, or you can include them at the same time, which might be unreasonable if you're not familiar with Ruby, and certainly wouldn't be reasonable if it were the case for all languages.
- When (albeit rarely) adding a CCK case to cover actually new functionality, it leaves a chicken and egg problem - you should include the Ruby step definitions, even though the API for Ruby may not exist yet.

### ✨ Do you have a proposal for making it better?

Move the Ruby steps and code into `cucumber-ruby`. Continue to publish a gem containing just the features, messages and reference steps, assuming that's still useful. The `cucumber-ruby` repo is then responsible for providing the step definitions and the test plumbing.

**Comment by luke-hill** [comment]
I "think" given how much I'm learning this might be a 2024 task.

For now it would be good / give me work to still try optimise things here and fix up issues. That would mean adding in some rubocop stuff to fix up a load of legacy code and streamline things whilst we wait to get things ported over. WDYT?

**Comment by davidjgoss** [comment]
Yeah I think it's fine to do it in whatever order makes sense, long as we don't make it any harder to do this move.

**Comment by luke-hill** [comment]
Done and released in v15 and v15.0.1 has a refactor in place
