### ISSUE TITLE
2 x minor discrepancies in CCK descriptions vs actions

### ISSUE THREAD

**Issue by luke-hill** [cucumber/compatibility-kit#46]
### 👓 What did you see?

1) Change `When a JPEG image is attached` to either attach a JPEG or rename it to PNG
cf: https://github.com/cucumber/compatibility-kit/blob/main/devkit/samples/attachments/attachments.feature.ts#L49
2) Change `When a PDF document is attached with a filename` to attach the `document.pdf` file with a different name. Rename the cuke to `When a PDF document is attached as `renamed-document.pdf`
cf: https://github.com/cucumber/compatibility-kit/blob/main/devkit/samples/attachments/attachments.feature.ts#L57

### 🔬 How could we reproduce it?

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by luke-hill** [comment]
@davidjgoss are you happy for these changes (Global), to the CCK?

**Comment by davidjgoss** [comment]
@luke-hill LGTM!

**Comment by luke-hill** [comment]
Fixed in #52 Will be released shortly
