### ISSUE TITLE
How to depend on messages json schemas?

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/compatibility-kit#5]
In order to validate the ndjson are valid according the json schemas, we need a dependency on the schemas.

At the moment the schemas are only part of the monorepo, not published in any package or anything else.

Any idea how we could use those schemas? Create an unpublished npm package and depend on it using github? Publish a npm package dedicated to those schemas? Embed those schemas in the messages package? Something else?

**Comment by aurelien-reeves** [comment]
I suggest to embed the schemas within messages npm package. Any objection @mattwynne? @davidjgoss?

**Comment by mattwynne** [comment]
What are the options?

**Comment by davidjgoss** [comment]
> I suggest to embed the schemas within messages npm package

Makes sense to me.

**Comment by mattwynne** [comment]
That's what we've decided to do: https://github.com/cucumber/common/pull/2010

We did consider publishing the schemas on the web, but it felt like too hairy of a yak shave for the purposes of moving this package out of the monorepo. We can always do that later if we feel it would be useful.
