### ISSUE TITLE
CCK: Investigate removal of Before-Hook in attachments feature

### ISSUE THREAD

**Issue by luke-hill** [cucumber/compatibility-kit#83]
### 🤔 What's the problem you've observed?

We have a `Before` hook in the `attachments.feature`. But it does nothing.

It "seems" as though we introduced this to help JVM.

### ✨ Do you have a proposal for making it better?

Are we able to remove this from both the devkit and all consumers, and just have the jvm implementer create a simple Before hook?

### 📚 Any additional context?

Shouldn't be affected by any reconciliation work (So we ignored it for now during the reconciliation issue)

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/developer_experience.md)*

**Comment by mpkorstanje** [comment]
Did you mean another file than `attachments.feature`?

**Comment by davidjgoss** [comment]
I think we're referring to this line in the reference step definitions https://github.com/cucumber/compatibility-kit/blob/main/devkit/samples/attachments/attachments.feature.ts#L5-L6 - unfortunately the origins are unclear even from the blame.

**Comment by mpkorstanje** [comment]
Okay. That makes sense.

Unlike JS, Java can't add methods to a class at runtime. So the scenario must be injected. And for some reason this is done as a method argument of the before hook.

I could look at  supporting dependency injection but that would be a long way away. I could also look at ignoring the hook message for this scenario. Probably easier.

If you want to remove it, go ahead.

**Comment by luke-hill** [comment]
I'd rather first get all the reconciliation work done, and then worry about other stuff later.

**Comment by luke-hill** [comment]
This "can" be the next item to look at, but again super low prio.

**Comment by luke-hill** [comment]
FYI I encountered this issue again after porting.

I removed the hook at my end, but there were 21 messages extra (10 scenarios each with a testStepStarted and testStepFinished and 1 hook).

Each of these 21 messages though was basically blank and doing nothing.

I guess the question is more along the lines of, could you have a scenario like mine where you check the messages types exactly for all scenarios and then maybe for attachments you could have a slight difference in your jUnit assertion? (A bit like when we run the retry scenario, we need to pass in extra arguments).

**Comment by mpkorstanje** [comment]
I would be in favor of removal. This is a non-conformance problem with Cucumber JVM and should be solved there. Either by making the cck pass, or by fixing the root cause.

**Comment by luke-hill** [comment]
Fixed by #102
