### ISSUE TITLE
Inconsistent TestStepResult for pending steps across implementations

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/compatibility-kit#88]
(Not an issue with CCK as such but have to raise it somewhere.)

Recent work on CCK has highlighted differences in how various Cucumber implementations output a `TestStepResult` message for a step that was marked pending by the user.

It's worth noting that the mechanism for marking a step pending also varies between implementations - Ruby and JVM do it by throwing, whereas JS and fake-cucumber return from the step function. This influences the current behaviour a little, I think.

Here's the current state of things (with `status` and timing fields omitted as these are all fine):

| field     | reference | cucumber-ruby                    | cucumber-jvm                       | cucumber-js |
|-----------|---------------|----------------------------------|------------------------------------|-------------|
| message   | (omitted)     | Name of pending exception | Stack trace from pending exception | (omitted)   |
| exception | (omitted)     | Pending exception                | Pending exception                  | (omitted)   |

**Comment by luke-hill** [comment]
Not sure if we want to comment here or in `messages` but the user supplied reason for both pending/skipped in cucumber ruby gets lost in the ether, it's not fully implemented to go through all the steps to message building

There is a message prop but it's kind of redundant

**Comment by davidjgoss** [comment]
@luke-hill what gets populated on the `message` prop then for the CCK to be failing on it?

**Comment by luke-hill** [comment]
There is a prop. Which is why it fails. The CCK has no message prop. So the failing test states "Too many keys produced"

**Comment by davidjgoss** [comment]
Ah so a prop with no value?

**Comment by luke-hill** [comment]
It says something like `message: " ()Cucumber::Pending"`

**Comment by davidjgoss** [comment]
This was discussed at the community call today. Upshot:

- `message` _should_ appear on result messages for pending steps - it may be a user-authored string explaining why the step isn't implemented yet, or just a default value from Cucumber (suggestion: `TODO`).
- `exception` should _not_ appear for pending steps - an exception may have been thrown but only as a vehicle to mark the step pending, and this should not be exposed to reporting.

So the work needed now is:

1. [ ]  Change `fake-cucumber` to include a `message` value for pending steps . Release.
2. [ ] Regenerate the reference messages in `compatibility-kit`. Release.
3. [ ] Make any required changes to `cucumber-(js|jvm|ruby)`. Release.
